{
 "title": "MySQL-Monitor Instances",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "compartment",
    "label": "Environment",
    "query": {
     "query": "select distinct compartment from config.target_database"
    }
   },
   {
    "name": "display_name",
    "label": "Instance Name",
    "query": {
     "query": "select display_name from config.target_database where compartment='$compartment' and start_date_time<=now() and end_date_time>=now()"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "select sum(is_success)/count(1)*100 \"Uptime (%)\" from `${compartment}#${display_name}`.db_status_log"
    }
   ]
  },
  {
   "title": "Performance Table (TABLE NAME: config.performance_schema_table)",
   "type": "table",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "select CASE \n    -- 1. Check if TODAY falls between the start and end DATES\n    WHEN (DATE(NOW()) BETWEEN DATE(start_date_time) AND DATE(end_date_time))\n    THEN 1 \n    ELSE 0 \n  END AS is_active, a.* from config.performance_schema_table a"
    }
   ]
  },
  {
   "title": "INCLUDE -- (TABLE NAME: config.include_performance_schema)",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "select CASE \n    -- 1. Check if TODAY falls between the start and end DATES\n    WHEN (DATE(NOW()) BETWEEN DATE(start_date_time) AND DATE(end_date_time))\n    THEN 1 \n    ELSE 0 \n  END AS is_active, a.table_name, a.start_date_time, a.end_date_time, a.created_by, a.creation_date, a.last_updated_by, a.last_update_date \n  from config.include_performance_schema a where compartment='${compartment}' and display_name='${display_name}'"
    }
   ]
  },
  {
   "title": "Active Session History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 6 },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "SELECT logtime, CAST(VARIABLE_VALUE AS DECIMAL(10,2)) \"Connections\"\nFROM `${compartment}#${display_name}`.global_status\nwhere logtime > NOW() - INTERVAL 6 HOUR and VARIABLE_NAME in ('Threads_connected');"
    },
    {
     "dataset": "config",
     "rawSql": "SELECT logtime, CAST(VARIABLE_VALUE AS DECIMAL(10,2)) \"Abort Connect\"\nFROM `${compartment}#${display_name}`.global_status\nwhere logtime > NOW() - INTERVAL 6 HOUR and VARIABLE_NAME in ('Aborted_connects');"
    }
   ]
  },
  {
   "title": "EXCLUDE -- (TABLE NAME: config.exclude_performance_schema)",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 11 },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "select CASE \n    -- 1. Check if TODAY falls between the start and end DATES\n    WHEN (DATE(NOW()) BETWEEN DATE(start_date_time) AND DATE(end_date_time))\n    THEN 1 \n    ELSE 0 \n  END AS is_active, a.table_name, a.start_date_time, a.end_date_time, a.created_by, a.creation_date, a.last_updated_by, a.last_update_date  \n  from config.exclude_performance_schema a where compartment='${compartment}' and display_name='${display_name}'"
    }
   ]
  },
  {
   "title": "Buffer Pool Size (GB)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "SELECT VARIABLE_VALUE / 1024 / 1024 / 1024 AS size_gb\nFROM `${compartment}#${display_name}`.global_variables \nWHERE VARIABLE_NAME = 'innodb_buffer_pool_size' and logtime=(select max(logtime) from `${compartment}#${display_name}`.global_variables)\n"
    }
   ]
  },
  {
   "title": "Buffer Pool Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "SELECT (1 - (SUM(IF(VARIABLE_NAME = 'Innodb_buffer_pool_reads', VARIABLE_VALUE, 0)) / \nSUM(IF(VARIABLE_NAME = 'Innodb_buffer_pool_read_requests', VARIABLE_VALUE, 1)))) * 100 AS hit_ratio \nFROM `${compartment}#${display_name}`.global_status \nWHERE VARIABLE_NAME IN ('Innodb_buffer_pool_read_requests', 'Innodb_buffer_pool_reads') and logtime > NOW() - INTERVAL 1 HOUR;"
    }
   ]
  },
  {
   "title": "Database Size Statistics",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "SELECT sum(data_mb) AS `Data Size (MB)`, sum(index_mb) AS `Index Size (MB)`, sum(data_mb) + sum(index_mb) AS \"Total Size (MB)\"\n    FROM `${compartment}#${display_name}`.TABLES where logtime=(select max(logtime) from `${compartment}#${display_name}`.TABLES)\n                          \n\n"
    }
   ]
  },
  {
   "title": "Top 20 Internal buffers Consuming RAM",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 23 },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "SELECT EVENT_NAME \"Event\", (CURRENT_NUMBER_OF_BYTES_USED/1024/1024/1024) AS current_mem\nFROM `${compartment}#${display_name}`.memory_summary_global_by_event_name\nWHERE CURRENT_NUMBER_OF_BYTES_USED > 0 and \nlogtime=(select max(logtime) from `${compartment}#${display_name}`.memory_summary_global_by_event_name)\nORDER BY CURRENT_NUMBER_OF_BYTES_USED DESC\nLIMIT 20;\n"
    }
   ]
  },
  {
   "title": "Top 10 High CPU Latency",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 23 },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "SELECT DIGEST_TEXT, COUNT_STAR, \n       FORMAT_PICO_TIME(SUM_TIMER_WAIT) AS total_latency,\n       FORMAT_PICO_TIME(AVG_TIMER_WAIT) AS avg_latency\nFROM `${compartment}#${display_name}`.events_statements_summary_by_digest\nWHERE logtime=(select max(logtime) from `${compartment}#${display_name}`.events_statements_summary_by_digest)\nORDER BY SUM_TIMER_WAIT DESC LIMIT 10;\n"
    }
   ]
  },
  {
   "title": "Database User Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "SELECT *\nFROM `${compartment}#${display_name}`.users\nWHERE logtime=(select max(logtime) from `${compartment}#${display_name}`.users)\n"
    }
   ]
  },
  {
   "title": "Top 20 High Latency SQL Statements",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "SELECT \n    DIGEST_TEXT,\n    COUNT_STAR AS execution_count,\n    FORMAT_PICO_TIME(SUM_TIMER_WAIT) AS total_latency,\n    FORMAT_PICO_TIME(AVG_TIMER_WAIT) AS avg_latency,\n    FORMAT_PICO_TIME(MAX_TIMER_WAIT) AS max_latency,\n    SUM_ROWS_EXAMINED AS total_rows_scanned\nFROM `${compartment}#${display_name}`.events_statements_summary_by_digest\nWHERE logtime=(select max(logtime) from `${compartment}#${display_name}`.events_statements_summary_by_digest)\nORDER BY SUM_TIMER_WAIT DESC\nLIMIT 20;\n\n"
    }
   ]
  },
  {
   "title": "Replication Lag ",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "SELECT logtime, source_ip, target_ip, channel_name, lag_seconds from replica.replication_lag \nwhere source_ip=(select ip_address from config.target_database where display_name='${display_name}')\norder by logtime desc limit 60"
    }
   ]
  }
 ]
}