{
 "title": "MySQL-Monitor HeatWave",
 "time": { "from": "2026-03-14T05:16:20.216Z", "to": "2026-03-14T08:16:20.921Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "region", "label": "OCI Region", "query": "regions()" },
   { "name": "compartment", "label": "OCI Compartment", "query": "compartments()" },
   {
    "name": "namespace",
    "query": "namespaces($region,$compartment)"
   },
   {
    "name": "resourcegroup",
    "query": "resourcegroups($region, $compartment, $namespace)"
   },
   {
    "name": "dimension",
    "label": "Instance",
    "query": "dimensions($region, $compartment, $namespace, $metric, $resourcegroup)"
   },
   {
    "name": "metric",
    "query": "metrics($region,$compartment, $namespace, $resourcegroup)"
   },
   {
    "name": "mysql_compartment",
    "label": "MySQL Compartment",
    "query": "select SUBSTRING_INDEX(TRIM('$compartment'), ' ', -1)"
   },
   {
    "name": "mysql_instance",
    "label": "MySQL Compartment",
    "query": "select replace(SUBSTRING_INDEX(TRIM(replace('$dimension','=',' ')), ' ', -1),'\"','')"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "### MySQL HeatWave Database Management\n"
   }
  },
  {
   "title": "Buffer pool hit ratio",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "`HanantoWicaksono_sandbox#test-2`",
     "rawSql": "SELECT (1 - (SUM(IF(VARIABLE_NAME = 'Innodb_buffer_pool_reads', VARIABLE_VALUE, 0)) / SUM(IF(VARIABLE_NAME = 'Innodb_buffer_pool_read_requests', VARIABLE_VALUE, 1)))) * 100 AS hit_ratio FROM `${mysql_compartment}#${mysql_instance}`.global_status \nWHERE VARIABLE_NAME IN ('Innodb_buffer_pool_read_requests', 'Innodb_buffer_pool_reads') and logtime > NOW() - INTERVAL 1 HOUR;"
    }
   ]
  },
  {
   "title": "CPU Utilisation ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 6, "y": 2 },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "resourceType=\"mysql\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "{{resourceName}}",
     "metric": "CpuUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "CpuUtilization[1m]{resourceType=\"mysql\",$dimension}.max()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "max()",
     "statisticLabel": "maximum",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "OCPU Allocated ",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 8, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Unit" } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "resourceType=\"mysql\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "{{resourceName}}",
     "metric": "OCPUsAllocated",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "OCPUsAllocated[1m]{resourceType=\"mysql\",$dimension}.max()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "max()",
     "statisticLabel": "maximum",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Storage Used per day",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 day",
     "legendFormat": "{{resourceName}} ",
     "metric": "StorageUsed",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "StorageUsed[1d]{$dimension}.sum()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "sum()",
     "statisticLabel": "sum",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 6, "y": 14 },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "resourceType=\"mysql\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "legendFormat": "{{hostName}} ",
     "metric": "MemoryUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "MemoryUtilization[1m]{resourceType=\"mysql\",$dimension}.max()",
     "queryTextRaw": "MemoryUtilization[5m]{resourceName=\"test-2\", resourceType=\"mysql\"}.max()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "max()",
     "statisticLabel": "maximum",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "resourceType=\"mysql\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "{{resourceName}}",
     "metric": "MemoryUsed",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "MemoryUsed[1m]{resourceType=\"mysql\",$dimension}.max()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "max()",
     "statisticLabel": "maximum",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Storage Utilisation per day",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 day",
     "legendFormat": "{{resourceName}}",
     "metric": "StorageUsed",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "StorageUsed[1d]{$dimension}.max()",
     "queryTextRaw": "StorageUtilization[240m].mean()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "max()",
     "statisticLabel": "maximum",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Connection Statistics",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 26 },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "{{resourceName}}",
     "metric": "CurrentConnections",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "CurrentConnections[1m]{$dimension}.max()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "max()",
     "statisticLabel": "maximum",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "DB Volume Write Bytes",
   "type": "gauge",
   "description": "This represents the total time spent by user sessions either actively waiting for a resource (such as I/O, CPU, or locks) or actually using the CPU to process database work.",
   "gridPos": { "h": 8, "w": 14, "x": 9, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "legendFormat": "Hostname: {{hostName}}",
     "metric": "DbVolumeWriteBytes",
     "metricNames": "$resourcegroup",
     "metricNamesFromNS": "$namespace",
     "namespace": "$namespace",
     "queryText": "DbVolumeWriteBytes[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "DB Volume Read Bytes",
   "type": "gauge",
   "description": "This represents the total time spent by user sessions either actively waiting for a resource (such as I/O, CPU, or locks) or actually using the CPU to process database work.",
   "gridPos": { "h": 8, "w": 14, "x": 9, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "legendFormat": "Hostname: {{hostName}}",
     "metric": "DbVolumeReadBytes",
     "metricNames": "$resourcegroup",
     "metricNamesFromNS": "$namespace",
     "namespace": "$namespace",
     "queryText": "DbVolumeReadBytes[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "NetworkReceiveBytes",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "{{resourceName}}",
     "metric": "NetworkReceiveBytes",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "NetworkReceiveBytes[1m]{$dimension}.max()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "max()",
     "statisticLabel": "maximum",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "NetworkTransmitBytes",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 12, "x": 11, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "{{resourceName}}",
     "metric": "NetworkTransmitBytes",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "NetworkTransmitBytes[1m]{$dimension}.max()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "max()",
     "statisticLabel": "maximum",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "HeatWaveHealth",
   "type": "state-timeline",
   "gridPos": { "h": 26, "w": 7, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "Auto",
     "legendFormat": "{{resourceName}}",
     "metric": "HeatWaveHealth",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "HeatWaveHealth[1m]{$dimension}.avg()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "avg()",
     "statisticLabel": "average",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "HeatWave Data Load Progress",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 16, "x": 7, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [ "$dimension" ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "{{resourceName}}",
     "metric": "HeatWaveDataLoadProgress",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "HeatWaveDataLoadProgress[1m]{$dimension}.max()",
     "queryTextRaw": "HeatWaveDataLoadProgress[1m]{resourceName=\"test-2\",}.max()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "max()",
     "statisticLabel": "maximum",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "HeatWave CPU Utilisation ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 16, "x": 7, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "resourceType=\"heatwave\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "{{hostName}} ",
     "metric": "CpuUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "CpuUtilization[1m]{resourceType=\"heatwave\",$dimension}.max()",
     "queryTextRaw": "CpuUtilization[1m]{resourceName=\"test-2\", resourceType=\"heatwave\"}.max()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "max()",
     "statisticLabel": "maximum",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "HeatWave Memory Utilisation ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 16, "x": 7, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "resourceType=\"heatwave\"",
      "$dimension"
     ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "legendFormat": "{{hostName}} ",
     "metric": "MemoryUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "MemoryUtilization[1m]{resourceType=\"heatwave\",$dimension}.max()",
     "queryTextRaw": "CpuUtilization[1m]{resourceName=\"test-2\", resourceType=\"heatwave\"}.max()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "max()",
     "statisticLabel": "maximum",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "HeatWave Overall Status Captured by Performance Schema",
   "type": "table",
   "gridPos": { "h": 18, "w": 10, "x": 0, "y": 82 },
   "targets": [
    {
     "dataset": "`HanantoWicaksono_sandbox#instance-1`",
     "rawSql": "select logtime, VARIABLE_NAME, VARIABLE_VALUE from `${mysql_compartment}#${mysql_instance}`.global_status\nwhere VARIABLE_NAME like 'rapid%' and logtime=(select max(logtime) from `${mysql_compartment}#${mysql_instance}`.global_status)"
    }
   ]
  },
  {
   "title": "RAPID Table Status from Performance Schema",
   "type": "table",
   "gridPos": { "h": 19, "w": 11, "x": 12, "y": 82 },
   "targets": [
    {
     "dataset": "`HanantoWicaksono_sandbox#instance-1`",
     "rawSql": "SELECT rpd_table_id.logtime logtime, schema_name, table_NAME, NROWS, LOAD_STATUS, SIZE_BYTES, QUERY_COUNT,LAST_QUERIED,\nLOAD_TYPE, LOAD_START_TIMESTAMP, LOAD_END_TIMESTAMP, RECOVERY_SOURCE FROM `${mysql_compartment}#${mysql_instance}`.rpd_tables,\n`${mysql_compartment}#${mysql_instance}`.rpd_table_id WHERE rpd_tables.ID = rpd_table_id.ID\nand rpd_tables.logtime=(select max(logtime) from `${mysql_compartment}#${mysql_instance}`.rpd_tables) and\nrpd_table_id.logtime=(select max(logtime) from `${mysql_compartment}#${mysql_instance}`.rpd_table_id);"
    }
   ]
  },
  {
   "title": "Top 100 Poor SQL Execution",
   "type": "table",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 101 },
   "targets": [
    {
     "dataset": "`HanantoWicaksono_sandbox#instance-1`",
     "rawSql": "SELECT \n    digest_text AS query, \n    count_star AS execution_count, \n    avg_timer_wait / 1000000000000 AS avg_time_sec,\n    max_timer_wait / 1000000000000 AS max_time_sec,\n    last_seen\nFROM `${mysql_compartment}#${mysql_instance}`.events_statements_summary_by_digest \nwhere logtime=(select max(logtime) from `${mysql_compartment}#${mysql_instance}`.events_statements_summary_by_digest)\nORDER BY avg_timer_wait DESC \nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Managed READ REPLICA Channel Lag",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 114 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "resourceType=\"replica\""
     ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "metric": "ChannelLag",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "ChannelLag[1m]{resourceName =~ \"${mysql_instance}-REPLICA-*\"}.max()",
     "queryTextRaw": "ChannelLag[1m]{resourceName =~ \"${mysql_instance}-REPLICA-*\"}.max()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "max()",
     "statisticLabel": "maximum",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Managed READ REPLICA CPU Utilisation ",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 11, "x": 12, "y": 114 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "dimensionValues": [
      "resourceType=\"replica\""
     ],
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "metric": "CpuUtilization",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "CpuUtilization[1m]{resourceName =~ \"${mysql_instance}-REPLICA-*\"}.max()",
     "queryTextRaw": "CpuUtilization[1m]{resourceName =~ \"${mysql_instance}-REPLICA-*\"}.max()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "max()",
     "statisticLabel": "maximum",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "Replication Lag Time to Time",
   "type": "table",
   "gridPos": { "h": 20, "w": 23, "x": 0, "y": 127 },
   "targets": [
    {
     "dataset": "`HanantoWicaksono_sandbox#instance-1`",
     "rawSql": "SELECT logtime, source_ip, target_ip, channel_name, lag_seconds from replica.replication_lag \nwhere source_ip=(select ip_address from config.target_database where display_name='${mysql_instance}')\norder by logtime desc limit 60"
    }
   ]
  }
 ]
}