{
 "title": "MySQL-Monitor Group Replication",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "compartment",
    "label": "Environment",
    "query": {
     "query": "select distinct compartment from config.target_database"
    }
   },
   {
    "name": "display_name",
    "label": "Instance Name",
    "query": {
     "query": "select display_name from config.target_database where compartment='$compartment' and start_date_time<=now() and end_date_time>=now()"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Group Replication Variables ",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "SELECT *\nFROM `${compartment}#${display_name}`.global_variables\nWHERE logtime=(select max(logtime) from `${compartment}#${display_name}`.global_variables) and VARIABLE_NAME like 'group_replication%'\norder by VARIABLE_NAME"
    }
   ]
  },
  {
   "title": "Group Replication Members ",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "SELECT *\nFROM `${compartment}#${display_name}`.replication_group_members\nWHERE logtime=(select max(logtime) from `${compartment}#${display_name}`.global_variables) \n"
    }
   ]
  },
  {
   "title": "Group Replication Member Stats ",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "SELECT *\nFROM `${compartment}#${display_name}`.replication_group_member_stats\nWHERE logtime=(select max(logtime) from `${compartment}#${display_name}`.global_variables) \n"
    }
   ]
  },
  {
   "title": "Replication Applier Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "SELECT *\nFROM `${compartment}#${display_name}`.replication_applier_status\nWHERE logtime=(select max(logtime) from `${compartment}#${display_name}`.global_variables) \n"
    }
   ]
  }
 ]
}