{
 "title": "MySQL-Monitor Control Fleet",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Register or Update Target Database",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Target Databases (TABLE NAME: config.target_database)",
   "type": "table",
   "gridPos": { "h": 14, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "select CASE \n    -- 1. Check if TODAY falls between the start and end DATES\n    WHEN (DATE(NOW()) BETWEEN DATE(start_date_time) AND DATE(end_date_time))\n    -- 2. Check if the CURRENT CLOCK TIME falls between the start and end TIMES\n    AND (CURTIME() BETWEEN start_time AND end_time) \n    THEN 1 \n    ELSE 0 \n  END AS is_active,\ncompartment \"Compartment\", display_name \"Instance\", ip_address \"IP Address\", \nport \"Port\", username \"Username\", minute_interval \"Interval (Min)\", days_retention \"Retention (Days)\", start_date_time \"Start Date\", \nend_date_time \"End Date\", start_time \"Schedule Start Time\", end_time \"Schedule End Time\", created_by \"Created By\", creation_date \"Date Creation\",  \nlast_updated_by \"Last Updated By\", last_update_date \"Last Update Date\" from config.target_database"
    }
   ]
  },
  {
   "title": "Register or Update Performance Tables",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "SELECT table_name\nFROM information_schema.TABLES \nWHERE table_schema = 'performance_schema';\n"
    }
   ]
  },
  {
   "title": "Performance Table (TABLE NAME: config.performance_schema_table)",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 14 },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "select CASE \n    -- 1. Check if TODAY falls between the start and end DATES\n    WHEN (DATE(NOW()) BETWEEN DATE(start_date_time) AND DATE(end_date_time))\n    THEN 1 \n    ELSE 0 \n  END AS is_active, a.* from config.performance_schema_table a"
    }
   ]
  },
  {
   "title": "INCLUDE -- Performance Tables",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 21 },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "SELECT table_name\nFROM information_schema.TABLES \nWHERE table_schema = 'performance_schema';\n"
    }
   ]
  },
  {
   "title": "INCLUDE -- (TABLE NAME: config.include_performance_schema)",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 21 },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "select CASE \n    -- 1. Check if TODAY falls between the start and end DATES\n    WHEN (DATE(NOW()) BETWEEN DATE(start_date_time) AND DATE(end_date_time))\n    THEN 1 \n    ELSE 0 \n  END AS is_active, a.* from config.include_performance_schema a"
    }
   ]
  },
  {
   "title": "EXCLUDE -- Performance Tables",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 29 },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "SELECT table_name\nFROM information_schema.TABLES \nWHERE table_schema = 'performance_schema';\n"
    }
   ]
  },
  {
   "title": "EXCLUDE -- (TABLE NAME: config.exclude_performance_schema)",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 29 },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "select CASE \n    -- 1. Check if TODAY falls between the start and end DATES\n    WHEN (DATE(NOW()) BETWEEN DATE(start_date_time) AND DATE(end_date_time))\n    THEN 1 \n    ELSE 0 \n  END AS is_active, a.* from config.exclude_performance_schema a"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 37 },
   "options": {
    "content": "### Repository DB Performance Statistics"
   }
  },
  {
   "title": "Buffer Pool Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "SELECT (1 - (SUM(IF(VARIABLE_NAME = 'Innodb_buffer_pool_reads', VARIABLE_VALUE, 0)) / \nSUM(IF(VARIABLE_NAME = 'Innodb_buffer_pool_read_requests', VARIABLE_VALUE, 1)))) * 100 AS hit_ratio \nFROM performance_schema.global_status \nWHERE VARIABLE_NAME IN ('Innodb_buffer_pool_read_requests', 'Innodb_buffer_pool_reads');"
    }
   ]
  },
  {
   "title": "Buffer Pool Size (GB)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "SELECT VARIABLE_VALUE / 1024 / 1024 / 1024 AS size_gb\nFROM performance_schema.global_variables \nWHERE VARIABLE_NAME = 'innodb_buffer_pool_size' \n"
    }
   ]
  },
  {
   "title": "Data Ingestion Size Statistic",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "SELECT\n            sum(ROUND(DATA_LENGTH / 1024 / 1024, 2)) AS `Data Size (MB)`,\n                sum(ROUND(INDEX_LENGTH / 1024 / 1024, 2)) AS `Index Size (MB)`,\n                    sum(ROUND((DATA_LENGTH + INDEX_LENGTH) / 1024 / 1024, 2)) AS `Total Size (MB)`\n                    FROM\n                        information_schema.TABLES\n                        WHERE\n                            TABLE_SCHEMA like '%#%' -- Replace with your database name\n                          \n\n"
    }
   ]
  },
  {
   "title": "Monitored Databases ordered by Size",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "SELECT\n    TABLE_SCHEMA AS `Database Target`,\n    sum(TABLE_ROWS) AS `Approx Rows`,\n    sum(ROUND(DATA_LENGTH / 1024 / 1024, 2)) AS `Data Size (MB)`,\n    sum(ROUND(INDEX_LENGTH / 1024 / 1024, 2)) AS `Index Size (MB)`,\n    sum(ROUND((DATA_LENGTH + INDEX_LENGTH) / 1024 / 1024, 2)) AS `Total Size (MB)`\nFROM\n    information_schema.TABLES\nWHERE\n    TABLE_SCHEMA like '%#%' -- Replace with your database name\nGROUP BY TABLE_SCHEMA\nORDER BY\n    (sum(ROUND(DATA_LENGTH / 1024 / 1024, 2)) + sum(ROUND(INDEX_LENGTH / 1024 / 1024, 2))) DESC\n\n"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "SELECT\n    TABLE_NAME AS `Table`,\n    sum(TABLE_ROWS) AS `Approx Rows`,\n    sum(ROUND(DATA_LENGTH / 1024 / 1024, 2)) AS `Data Size (MB)`,\n    sum(ROUND(INDEX_LENGTH / 1024 / 1024, 2)) AS `Index Size (MB)`,\n    sum(ROUND((DATA_LENGTH + INDEX_LENGTH) / 1024 / 1024, 2)) AS `Total Size (MB)`\nFROM\n    information_schema.TABLES\nWHERE\n    TABLE_SCHEMA like '%#%' -- Replace with your database name\nGROUP BY TABLE_NAME\nORDER BY\n    (sum(ROUND(DATA_LENGTH / 1024 / 1024, 2)) + sum(ROUND(INDEX_LENGTH / 1024 / 1024, 2))) DESC\n\n"
    }
   ]
  },
  {
   "title": "Top 20 High Latency SQL Statements",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "dataset": "config",
     "rawSql": "SELECT \n    DIGEST_TEXT,\n    COUNT_STAR AS execution_count,\n    FORMAT_PICO_TIME(SUM_TIMER_WAIT) AS total_latency,\n    FORMAT_PICO_TIME(AVG_TIMER_WAIT) AS avg_latency,\n    FORMAT_PICO_TIME(MAX_TIMER_WAIT) AS max_latency,\n    SUM_ROWS_EXAMINED AS total_rows_scanned\nFROM performance_schema.events_statements_summary_by_digest\nORDER BY SUM_TIMER_WAIT DESC\nLIMIT 20;\n\n"
    }
   ]
  }
 ]
}